### ISSUE TITLE
Error: [non-error-thrown] [object Object]

### ISSUE THREAD

**Issue by chmac** [hugojosefson/deno-run-simple#1]
Firstly, thanks a lot for simpe-run, it's really epic! 🧡 🧡 🧡

I'm seeing some errors produced like so:

    Error: [non-error-thrown] [object Object]

I can't see the contents of the error because I just get `[object Object]`. From looking at the code it looks like `run()` throws a non error if the script exits with a non zero code. Is there a way to unpack the error and get it logged? Or would it make sense to extend the error class and throw that?

**Comment by hugojosefson** [comment]
Thank you for the kind words!

I agree that the code should not throw something that isn't an `Error`. I will look into it :+1:

**Comment by chmac** [comment]
I had a quick look at the code and I think it's because `CommandFailure` doesn't extend `Error`. But I'm not sure if an `interface` can extend from `Error` or not...

**Comment by hugojosefson** [comment]
I think I fixed it. Would you please have a look at https://github.com/hugojosefson/deno-run-simple/pull/2, and see what you think?

**Comment by chmac** [comment]
Awesome, looks good to me! Thanks for sorting that out so quickly. 🚀

**Comment by hugojosefson** [comment]
> Awesome, looks good to me! Thanks for sorting that out so quickly. rocket

Thank you for the assist :)

Updated version deployed and available via:
```ts
import { run } from "https://deno.land/x/run_simple@1.2.0/mod.ts";
```
